repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--fix]
        files: ^package/
      - id: ruff-format
        files: ^package/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^package/src/
        additional_dependencies:
          - types-requests>=2.31
          - types-PyYAML>=6.0
